try{
    hello();
}
catch(err){
    console.log(err, "HOlala")
}
try{
    helloWorld();
}
catch{
    console.log('Esto es un error')
}